/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eIOSAppirater.h"


// For MIPs (and WP8) platform we do not have asm code for stack switching 
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eIOSAppiraterParams_t)(int appId, int usesUntilPrompt, int daysUntilPrompt, int daysRemindLater, int numSignificantEvents, const char * rateNowTitle, const char * rateNowText, const char * rateNowYesButton, const char * remindTitle, const char * remindText, const char * remindYesButton, const char * commonNoButton);
typedef       void(*s3eIOSAppiraterAppLaunched_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterAppEnteredForeground_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterUserDidSignificantEvent_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterRateApp_t)();

/**
 * struct that gets filled in by s3eIOSAppiraterRegister
 */
typedef struct s3eIOSAppiraterFuncs
{
    s3eIOSAppiraterParams_t m_s3eIOSAppiraterParams;
    s3eIOSAppiraterAppLaunched_t m_s3eIOSAppiraterAppLaunched;
    s3eIOSAppiraterAppEnteredForeground_t m_s3eIOSAppiraterAppEnteredForeground;
    s3eIOSAppiraterUserDidSignificantEvent_t m_s3eIOSAppiraterUserDidSignificantEvent;
    s3eIOSAppiraterRateApp_t m_s3eIOSAppiraterRateApp;
} s3eIOSAppiraterFuncs;

static s3eIOSAppiraterFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf2eb1843, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eIOSAppirater");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf2eb1843, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eIOSAppiraterAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void s3eIOSAppiraterParams(int appId, int usesUntilPrompt, int daysUntilPrompt, int daysRemindLater, int numSignificantEvents, const char * rateNowTitle, const char * rateNowText, const char * rateNowYesButton, const char * remindTitle, const char * remindText, const char * remindYesButton, const char * commonNoButton)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[0] func: s3eIOSAppiraterParams"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eIOSAppiraterParams(appId, usesUntilPrompt, daysUntilPrompt, daysRemindLater, numSignificantEvents, rateNowTitle, rateNowText, rateNowYesButton, remindTitle, remindText, remindYesButton, commonNoButton);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eIOSAppiraterAppLaunched(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[1] func: s3eIOSAppiraterAppLaunched"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eIOSAppiraterAppLaunched(canPromptForRating);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eIOSAppiraterAppEnteredForeground(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[2] func: s3eIOSAppiraterAppEnteredForeground"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eIOSAppiraterAppEnteredForeground(canPromptForRating);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eIOSAppiraterUserDidSignificantEvent(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[3] func: s3eIOSAppiraterUserDidSignificantEvent"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eIOSAppiraterUserDidSignificantEvent(canPromptForRating);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eIOSAppiraterRateApp()
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[4] func: s3eIOSAppiraterRateApp"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eIOSAppiraterRateApp();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
