/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eIOSAppiraterParams_t)(int appId, int usesUntilPrompt, int daysUntilPrompt, int daysRemindLater, int numSignificantEvents, const char * rateNowTitle, const char * rateNowText, const char * rateNowYesButton, const char * remindTitle, const char * remindText, const char * remindYesButton, const char * commonNoButton);
typedef       void(*s3eIOSAppiraterAppLaunched_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterAppEnteredForeground_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterUserDidSignificantEvent_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterRateApp_t)();

/**
 * struct that gets filled in by s3eIOSAppiraterRegister
 */
typedef struct s3eIOSAppiraterFuncs
{
    s3eIOSAppiraterParams_t m_s3eIOSAppiraterParams;
    s3eIOSAppiraterAppLaunched_t m_s3eIOSAppiraterAppLaunched;
    s3eIOSAppiraterAppEnteredForeground_t m_s3eIOSAppiraterAppEnteredForeground;
    s3eIOSAppiraterUserDidSignificantEvent_t m_s3eIOSAppiraterUserDidSignificantEvent;
    s3eIOSAppiraterRateApp_t m_s3eIOSAppiraterRateApp;
} s3eIOSAppiraterFuncs;
